export default {
  namespaced: true,
  state: {
    footer: [],
    appList: [
      {
        id: 1,
        admobAppId: "ca-app-pub-1234567890-0987654321",
        appName: "App 1 clock vault app",
        companyName: "My Company",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: true,
        useBanner: false,
        useIntertitial: true,
        useRewarded: false,
        coppa: true,
        crossPromo: false,
      },
      {
        id: 2,
        admobAppId: "pb-app-pub-1234567890-0987654321",
        appName: "App 2",
        companyName: "My Company",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: true,
        useBanner: false,
        useIntertitial: true,
        useRewarded: false,
        coppa: true,
        crossPromo: false,
      },
      {
        id: 3,
        admobAppId: "cn-app-pub-1234567890-0987654321",
        appName: "App 3",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: true,
        useBanner: false,
        useIntertitial: true,
        useRewarded: true,
        coppa: false,
        crossPromo: false,
      },
      {
        id: 4,
        admobAppId: "as-app-pub-1234567890-0987654321",
        appName: "App 4",
        companyName: "My Company",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: false,
        useBanner: true,
        useIntertitial: true,
        useRewarded: true,
        coppa: true,
        crossPromo: true,
      },
      {
        id: 5,
        admobAppId: "ca-app-pub-1234567890-0987654321",
        appName: "App 5",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: true,
        useBanner: false,
        useIntertitial: true,
        useRewarded: false,
        coppa: true,
        crossPromo: false,
      },
      {
        id: 6,
        admobAppId: "pb-app-pub-1234567890-0987654321",
        appName: "App 6",
        companyName: "My Company",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: true,
        useBanner: false,
        useIntertitial: true,
        useRewarded: false,
        coppa: true,
        crossPromo: false,
      },
      {
        id: 7,
        admobAppId: "cn-app-pub-1234567890-0987654321",
        appName: "App 7",
        companyName: "My Company",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: true,
        useBanner: false,
        useIntertitial: true,
        useRewarded: true,
        coppa: false,
        crossPromo: false,
      },
      {
        id: 8,
        admobAppId: "as-app-pub-1234567890-0987654321",
        appName: "App 8",
        companyName: "My Company",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: false,
        useBanner: true,
        useIntertitial: true,
        useRewarded: true,
        coppa: true,
        crossPromo: true,
      },
      {
        id: 9,
        admobAppId: "ca-app-pub-1234567890-0987654321",
        appName: "App 9",
        companyName: "My Company",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: true,
        useBanner: false,
        useIntertitial: true,
        useRewarded: false,
        coppa: true,
        crossPromo: false,
      },
      {
        id: 10,
        admobAppId: "pb-app-pub-1234567890-0987654321",
        appName: "App 10",
        companyName: "My Company",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: true,
        useBanner: false,
        useIntertitial: true,
        useRewarded: false,
        coppa: true,
        crossPromo: false,
      },
      {
        id: 11,
        admobAppId: "cn-app-pub-1234567890-0987654321",
        appName: "App 11",
        companyName: "My Company",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: true,
        useBanner: false,
        useIntertitial: true,
        useRewarded: true,
        coppa: false,
        crossPromo: false,
      },
      {
        id: 12,
        admobAppId: "as-app-pub-1234567890-0987654321",
        appName: "App 12",
        companyName: "My Company",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: false,
        useBanner: true,
        useIntertitial: true,
        useRewarded: true,
        coppa: true,
        crossPromo: true,
      },
      {
        id: 13,
        admobAppId: "ca-app-pub-1234567890-0987654321",
        appName: "App 13",
        companyName: "My Company",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: true,
        useBanner: false,
        useIntertitial: true,
        useRewarded: false,
        coppa: true,
        crossPromo: false,
      },
      {
        id: 14,
        admobAppId: "pb-app-pub-1234567890-0987654321",
        appName: "App 14",
        companyName: "My Company",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: true,
        useBanner: false,
        useIntertitial: true,
        useRewarded: false,
        coppa: true,
        crossPromo: false,
      },
      {
        id: 15,
        admobAppId: "cn-app-pub-1234567890-0987654321",
        appName: "App 15",
        companyName: "My Company",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: true,
        useBanner: false,
        useIntertitial: true,
        useRewarded: true,
        coppa: false,
        crossPromo: false,
      },
      {
        id: 16,
        admobAppId: "as-app-pub-1234567890-0987654321",
        appName: "App 16",
        companyName: "My Company",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: false,
        useBanner: true,
        useIntertitial: true,
        useRewarded: true,
        coppa: true,
        crossPromo: true,
      },
      {
        id: 17,
        admobAppId: "as-app-pub-1234567890-0987654321",
        appName: "App 17",
        companyName: "My Company",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: false,
        useBanner: true,
        useIntertitial: true,
        useRewarded: true,
        coppa: true,
        crossPromo: true,
      },
      {
        id: 18,
        admobAppId: "ca-app-pub-1234567890-0987654321",
        appName: "App 18",
        companyName: "My Company",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: true,
        useBanner: false,
        useIntertitial: true,
        useRewarded: false,
        coppa: true,
        crossPromo: false,
      },
      {
        id: 19,
        admobAppId: "pb-app-pub-1234567890-0987654321",
        appName: "App 19",
        companyName: "My Company",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: true,
        useBanner: false,
        useIntertitial: true,
        useRewarded: false,
        coppa: true,
        crossPromo: false,
      },
      {
        id: 20,
        admobAppId: "cn-app-pub-1234567890-0987654321",
        appName: "App 20",
        companyName: "My Company",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: true,
        useBanner: false,
        useIntertitial: true,
        useRewarded: true,
        coppa: false,
        crossPromo: false,
      },
      {
        id: 21,
        admobAppId: "as-app-pub-1234567890-0987654321",
        appName: "App 21",
        companyName: "My Company",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: false,
        useBanner: true,
        useIntertitial: true,
        useRewarded: true,
        coppa: true,
        crossPromo: true,
      },
      {
        id: 22,
        admobAppId: "ca-app-pub-1234567890-0987654321",
        appName: "App 22",
        companyName: "My Company",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: true,
        useBanner: false,
        useIntertitial: true,
        useRewarded: false,
        coppa: true,
        crossPromo: false,
      },
      {
        id: 23,
        admobAppId: "pb-app-pub-1234567890-0987654321",
        appName: "App 23",
        companyName: "My Company",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: true,
        useBanner: false,
        useIntertitial: true,
        useRewarded: false,
        coppa: true,
        crossPromo: false,
      },
      {
        id: 24,
        admobAppId: "cn-app-pub-1234567890-0987654321",
        appName: "App 24",
        companyName: "My Company",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: true,
        useBanner: false,
        useIntertitial: true,
        useRewarded: true,
        coppa: false,
        crossPromo: false,
      },
      {
        id: 25,
        admobAppId: "as-app-pub-1234567890-0987654321",
        appName: "App 25",
        companyName: "My Company",
        dau: 455,
        arpu: 0.015,
        immersions: 1463,
        ecpm: 4.13,
        est: 7.13,
        platform: "android",
        orientation: "landscape",
        published: false,
        useBanner: true,
        useIntertitial: true,
        useRewarded: true,
        coppa: true,
        crossPromo: true,
      },
    ],
    selectedId: null,
    isAdmobAppIdModalOpen: false,
    isModalAddApplicationOpen: false,
  },
  mutations: {
    changeSelectedId(state, id) {
      state.selectedId = id;
    },
    resetDropdown(state) {
      state.selectedId = null;
    },
    openAdmobAppIdModal(state) {
      state.isAdmobAppIdModalOpen = true;
      state.selectedId = null;
    },
    closeAdmobAppIdModal(state) {
      state.isAdmobAppIdModalOpen = false;
    },
    openModalAddApplication(state) {
      state.isModalAddApplicationOpen = true;
    },
    closeModalAddApplication(state) {
      state.isModalAddApplicationOpen = false;
    },
  },
};
