export default {
  namespaced: true,
  state: {
    mediationTableColumns: [
      {
        field: "appName",
        header: "App",
        sortable: true,
        style: { minWidth: "300px" },
        frozen: true,
        footer: "Totals:",
      },
      {
        field: "dau",
        header: "DAU",
        sortable: true,
        style: { width: "190px" },
        frozen: false,
        footer: "12320",
      },
      {
        field: "arpu",
        header: "ARPU",
        sortable: true,
        style: { width: "190px" },
        frozen: false,
        footer: "12320",
      },
      {
        field: "immersions",
        header: "Immersions",
        sortable: true,
        style: { width: "190px" },
        frozen: false,
        footer: "12320",
      },
      {
        field: "ecpm",
        header: "ECPM",
        sortable: true,
        style: { width: "195px" },
        frozen: false,
        footer: "12320",
      },
      {
        field: "est",
        header: "Est. Earnings",
        sortable: true,
        style: { width: "195px" },
        frozen: false,
        footer: "12320",
      },
    ],
    paymentsTableColumns: [
      {
        field: "year",
        header: "Year",
        sortable: false,
        style: { minWidth: "105px" },
        frozen: true,
      },
      {
        field: "month",
        header: "Month",
        sortable: false,
        style: { width: "110px" },
        frozen: false,
      },
      {
        field: "accuralSum",
        header: "Accural sum",
        sortable: false,
        style: { width: "170px" },
        frozen: false,
      },
      {
        field: "paymentDate",
        header: "Payment date",
        sortable: false,
        style: { width: "170px" },
        frozen: false,
      },
      {
        field: "paymentSum",
        header: "Payment sum",
        sortable: false,
        style: { width: "170px" },
        frozen: false,
      },
      {
        field: "currentBalance",
        header: "Current balance",
        sortable: false,
        style: { width: "185px" },
        frozen: false,
      },
      {
        field: "comment",
        header: "Comment",
        sortable: false,
        style: { width: "350px" },
        frozen: false,
      },
    ],
    applicationsTableColumns: [
      {
        field: "appName",
        header: "App",
        sortable: false,
        style: { minWidth: "216px" },
        frozen: true,
      },
      {
        field: "platform",
        header: "Platform",
        sortable: false,
        style: { width: "110px" },
        frozen: false,
      },
      {
        field: "orientation",
        header: "Orientation",
        sortable: false,
        style: { width: "132px" },
        frozen: false,
      },
      {
        field: "published",
        header: "Published",
        sortable: false,
        style: { width: "119px" },
        frozen: false,
      },
      {
        field: "useBanner",
        header: "Use Banner",
        sortable: false,
        style: { width: "98px" },
        frozen: false,
      },
      {
        field: "useIntertitial",
        header: "Use intertitial",
        sortable: false,
        style: { width: "114px" },
        frozen: false,
      },
      {
        field: "useRewarded",
        header: "Use Rewarded",
        sortable: false,
        style: { width: "121px" },
        frozen: false,
      },
      {
        field: "coppa",
        header: "Coppa",
        sortable: false,
        style: { minWidth: "93px" },
        frozen: false,
      },
      {
        field: "crossPromo",
        header: "Cross promo",
        sortable: false,
        style: { width: "190px" },
        frozen: false,
      },
      {
        field: "appTableActions",
        header: "",
        sortable: false,
        style: { minWidth: "67px" },
        frozen: false,
      },
    ],
    creativesTableColumns: [
      {
        field: "creativeName",
        header: "Creative name",
        sortable: false,
        style: { minWidth: "266px" },
        frozen: true,
      },
      {
        field: "bundleCode",
        header: "Bundle Code",
        sortable: false,
        style: { width: "160px" },
        frozen: false,
      },
      {
        field: "languages",
        header: "Languages",
        sortable: false,
        style: { width: "340px" },
        frozen: false,
      },
      {
        field: "types",
        header: "Types",
        sortable: false,
        style: { width: "120px" },
        frozen: false,
      },
      {
        field: "imagePreview",
        header: "Image Prewiew",
        sortable: false,
        style: { width: "190px" },
        frozen: false,
      },
      {
        field: "videoPreview",
        header: "Video Prewiew",
        sortable: false,
        style: { width: "184px" },
        frozen: false,
      },
    ],
    campaignsTableColumns: [
      {
        field: "status",
        header: "Status",
        sortable: false,
        style: { minWidth: "80px" },
        frozen: true,
      },
      {
        field: "campaignName",
        header: "Campaign Name",
        sortable: false,
        style: { width: "160px" },
        frozen: false,
      },
      {
        field: "startDate",
        header: "Start date",
        sortable: false,
        style: { width: "120px" },
        frozen: false,
      },
      {
        field: "languages",
        header: "Languages",
        sortable: false,
        style: { width: "155px" },
        frozen: false,
      },
      {
        field: "locations",
        header: "Locations",
        sortable: false,
        style: { width: "155px" },
        frozen: false,
      },
      {
        field: "creativesCount",
        header: "Creatives count",
        sortable: false,
        style: { width: "110px" },
        frozen: false,
      },
      {
        field: "premiumId",
        header: "PremiumId",
        sortable: false,
        style: { width: "120px" },
        frozen: false,
      },
      {
        field: "applications",
        header: "Applications",
        sortable: false,
        style: { width: "130px" },
        frozen: false,
      },
      {
        field: "creatives",
        header: "Creatives",
        sortable: false,
        style: { width: "105px" },
        frozen: false,
      },
      {
        field: "frequency",
        header: "Frequency",
        sortable: false,
        style: { width: "125px" },
        frozen: false,
      },
    ],
  },
  mutations: {},
  getters: {},
  actions: {},
};
